guard 'spork' do
  watch(%r%^config/application.rb$%)
  watch(%r%^config/environment.rb$%)
  watch(%r%^config/environments/.*\.rb$%)
  watch(%r%^config/initializers/.*\.rb$%)
  watch(%r%^spec/spec_helper.rb%)
end
